# Generated by Django 5.0.6 on 2024-11-26 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_condition_day_ken_alter_like_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppost',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.condition'),
        ),
        migrations.AddField(
            model_name='shoppost',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.day'),
        ),
        migrations.AddField(
            model_name='shoppost',
            name='ken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.ken'),
        ),
    ]
